-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema yourpc_test
-- -----------------------------------------------------

DROP DATABASE IF EXISTS `yourpc_test`;
CREATE DATABASE IF NOT EXISTS `yourpc_test`;
USE `yourpc_test`;

-- -----------------------------------------------------
-- Table `LOCALE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LOCALE` (
	`ID` VARCHAR(40) NOT NULL,
    `NAME` VARCHAR(80) NOT NULL UNIQUE,
    PRIMARY KEY (`ID`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------
-- Table `COUNTRY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COUNTRY` (
  `ID` CHAR(3) NOT NULL,
  `NAME` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `PROVINCE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROVINCE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(40) NOT NULL,
  `COUNTRY_ID` CHAR(3) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_PROVINCE_COUNTRY1_idx` (`COUNTRY_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PROVINCE_COUNTRY1`
    FOREIGN KEY (`COUNTRY_ID`)
    REFERENCES `COUNTRY` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `CITY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CITY` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(80) NOT NULL,
  `PROVINCE_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_CITY_PROVINCE1_idx` (`PROVINCE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_CITY_PROVINCE1`
    FOREIGN KEY (`PROVINCE_ID`)
    REFERENCES `PROVINCE` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `DOCUMENT_TYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DOCUMENT_TYPE` (
  `ID` CHAR(3) NOT NULL,
  `NAME` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `CUSTOMER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CUSTOMER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(80) NOT NULL,
  `LAST_NAME1` VARCHAR(80) NOT NULL,
  `LAST_NAME2` VARCHAR(80) NULL DEFAULT NULL,
  `DOCUMENT_TYPE_ID` CHAR(3) NOT NULL,
  `DOCUMENT_NUMBER` VARCHAR(30) NOT NULL,
  `PHONE` VARCHAR(20) NOT NULL,
  `EMAIL` VARCHAR(128) NOT NULL,
  `PASSWORD` VARCHAR(256) NOT NULL,
  `CREATION_DATE` DATETIME NOT NULL,
  `DELETION_DATE` DATETIME NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `PHONE_UNIQUE` (`PHONE` ASC) VISIBLE,
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC) VISIBLE,
  INDEX `fk_CUSTOMER_DOCUMENT_TYPE1_idx` (`DOCUMENT_TYPE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_CUSTOMER_DOCUMENT_TYPE1`
    FOREIGN KEY (`DOCUMENT_TYPE_ID`)
    REFERENCES `DOCUMENT_TYPE` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `EMPLOYEE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EMPLOYEE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `SUPERVISOR_ID` INT NULL DEFAULT NULL,
  `FIRST_NAME` VARCHAR(80) NOT NULL,
  `LAST_NAME1` VARCHAR(80) NOT NULL,
  `LAST_NAME2` VARCHAR(80) NULL DEFAULT NULL,
  `DOCUMENT_TYPE_ID` CHAR(3) NOT NULL,
  `DOCUMENT_NUMBER` VARCHAR(30) NOT NULL,
  `PHONE` VARCHAR(20) NOT NULL,
  `EMAIL` VARCHAR(128) NOT NULL,
  `USERNAME` VARCHAR(80) NOT NULL,
  `PASSWORD` VARCHAR(256) NOT NULL,
  `CREATION_DATE` DATETIME NOT NULL,
  `TERMINATION_DATE` DATETIME NULL,
  `IBAN` VARCHAR(34) NOT NULL,
  `BIC` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC) VISIBLE,
  INDEX `fk_EMPLOYEE_DOCUMENT_TYPE1_idx` (`DOCUMENT_TYPE_ID` ASC) VISIBLE,
  INDEX `fk_EMPLOYEE_EMPLOYEE1_idx` (`SUPERVISOR_ID` ASC) VISIBLE,
  UNIQUE INDEX `USERNAME_UNIQUE` (`USERNAME` ASC) VISIBLE,
  CONSTRAINT `fk_EMPLOYEE_DOCUMENT_TYPE1`
    FOREIGN KEY (`DOCUMENT_TYPE_ID`)
    REFERENCES `DOCUMENT_TYPE` (`ID`),
  CONSTRAINT `fk_EMPLOYEE_EMPLOYEE1`
    FOREIGN KEY (`SUPERVISOR_ID`)
    REFERENCES `EMPLOYEE` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ADDRESS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ADDRESS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ID` INT NULL DEFAULT NULL,
  `EMPLOYEE_ID` INT NULL DEFAULT NULL,
  `STREET_NAME` VARCHAR(128) NOT NULL,
  `STREET_NUMBER` SMALLINT NULL,
  `FLOOR` SMALLINT NULL DEFAULT NULL,
  `DOOR` VARCHAR(10) NULL DEFAULT NULL,
  `ZIP_CODE` VARCHAR(20) NOT NULL,
  `CITY_ID` INT NOT NULL,
  `IS_DEFAULT` TINYINT(1) NULL,
  `IS_BILLING` TINYINT(1) NULL,
  `CREATION_DATE` DATETIME NOT NULL,
  `DELETION_DATE` DATETIME NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_ADDRESS_CITY1_idx` (`CITY_ID` ASC) VISIBLE,
  INDEX `fk_ADDRESS_CUSTOMER1_idx` (`CUSTOMER_ID` ASC) VISIBLE,
  INDEX `fk_ADDRESS_EMPLOYEE1_idx` (`EMPLOYEE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_ADDRESS_CITY1`
    FOREIGN KEY (`CITY_ID`)
    REFERENCES `CITY` (`ID`),
  CONSTRAINT `fk_ADDRESS_CUSTOMER1`
    FOREIGN KEY (`CUSTOMER_ID`)
    REFERENCES `CUSTOMER` (`ID`),
  CONSTRAINT `fk_ADDRESS_EMPLOYEE1`
    FOREIGN KEY (`EMPLOYEE_ID`)
    REFERENCES `EMPLOYEE` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `CATEGORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CATEGORY` (
  `ID` SMALLINT NOT NULL,
  `PARENT_ID` SMALLINT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_category_category1_idx` (`PARENT_ID` ASC) VISIBLE,
  CONSTRAINT `fk_category_category1`
    FOREIGN KEY (`PARENT_ID`)
    REFERENCES `CATEGORY` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------
-- Table `yourpc_test`.`CATEGORY_LOCALE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CATEGORY_LOCALE` (
	`ID` INT NOT NULL AUTO_INCREMENT,
    `CATEGORY_ID` SMALLINT NOT NULL,
    `LOCALE_ID` VARCHAR(40) NOT NULL,
    NAME VARCHAR(80) NOT NULL,
    PRIMARY KEY (`ID`),
	UNIQUE INDEX `CATEGORY_ID_LOCALE_ID_UNIQUE` (`CATEGORY_ID` ASC, `LOCALE_ID` ASC) VISIBLE,
    CONSTRAINT `fk_CATEGORY_CATEGORY_LOCALE`
		FOREIGN KEY (`CATEGORY_ID`)
        REFERENCES `yourpc_test`.`CATEGORY` (`ID`)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
	CONSTRAINT `fk_CATEGORY_LOCALE_LOCALE`
		FOREIGN KEY (`LOCALE_ID`)
        REFERENCES `yourpc_test`.`LOCALE` (`ID`)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
	)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------
-- Table `DEPARTMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEPARTMENT` (
  `ID` CHAR(3) NOT NULL,
  `NAME` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `EMPLOYEE_DEPARTMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EMPLOYEE_DEPARTMENT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `EMPLOYEE_ID` INT NOT NULL,
  `DEPARTMENT_ID` CHAR(3) NOT NULL,
  `START_DATE` DATE NOT NULL,
  `END_DATE` DATE NULL DEFAULT NULL,
  INDEX `fk_EMPLOYEE_has_DEPARTMENT_DEPARTMENT1_idx` (`DEPARTMENT_ID` ASC) VISIBLE,
  INDEX `fk_EMPLOYEE_has_DEPARTMENT_EMPLOYEE1_idx` (`EMPLOYEE_ID` ASC) VISIBLE,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_EMPLOYEE_has_DEPARTMENT_DEPARTMENT1`
    FOREIGN KEY (`DEPARTMENT_ID`)
    REFERENCES `DEPARTMENT` (`ID`),
  CONSTRAINT `fk_EMPLOYEE_has_DEPARTMENT_EMPLOYEE1`
    FOREIGN KEY (`EMPLOYEE_ID`)
    REFERENCES `EMPLOYEE` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ORDER_STATE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ORDER_STATE` (
  `ID` CHAR(3) NOT NULL,
  `NAME` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `DESCR_UNIQUE` (`NAME` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `CUSTOMER_ORDER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CUSTOMER_ORDER` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `ORDER_STATE_ID` CHAR(3) NOT NULL,
  `CUSTOMER_ID` INT NOT NULL,
  `ORDER_DATE` DATETIME NOT NULL,
  `TRACKING_NUMBER` VARCHAR(40) NULL DEFAULT NULL,
  `BILLING_ADDRESS_ID` INT NOT NULL,
  `SHIPPING_ADDRESS_ID` INT NOT NULL,
  `INVOICE_TOTAL` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_ORDER_ORDER_STATE1_idx` (`ORDER_STATE_ID` ASC) VISIBLE,
  INDEX `fk_ORDER_ADDRESS1_idx` (`BILLING_ADDRESS_ID` ASC) VISIBLE,
  INDEX `fk_ORDER_ADDRESS2_idx` (`SHIPPING_ADDRESS_ID` ASC) VISIBLE,
  INDEX `fk_ORDER_CUSTOMER1_idx` (`CUSTOMER_ID` ASC) VISIBLE,
  CONSTRAINT `fk_ORDER_ADDRESS1`
    FOREIGN KEY (`BILLING_ADDRESS_ID`)
    REFERENCES `ADDRESS` (`ID`),
  CONSTRAINT `fk_ORDER_ADDRESS2`
    FOREIGN KEY (`SHIPPING_ADDRESS_ID`)
    REFERENCES `ADDRESS` (`ID`),
  CONSTRAINT `fk_ORDER_CUSTOMER1`
    FOREIGN KEY (`CUSTOMER_ID`)
    REFERENCES `CUSTOMER` (`ID`),
  CONSTRAINT `fk_ORDER_ORDER_STATE1`
    FOREIGN KEY (`ORDER_STATE_ID`)
    REFERENCES `ORDER_STATE` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `PRODUCT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRODUCT` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `CATEGORY_ID` SMALLINT NOT NULL,
  `LAUNCH_DATE` DATETIME NULL DEFAULT NULL,
  `DISCONTINUATION_DATE` DATETIME NULL,
  `STOCK` INT NOT NULL DEFAULT '0',
  `PURCHASE_PRICE` DECIMAL(10,2) NOT NULL,
  `SALE_PRICE` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `REPLACEMENT_ID` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_PRODUCTO_CATEGORIA1_idx` (`CATEGORY_ID` ASC) VISIBLE,
  INDEX `fk_PRODUCT_PRODUCT1_idx` (`REPLACEMENT_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCT_PRODUCT1`
    FOREIGN KEY (`REPLACEMENT_ID`)
    REFERENCES `PRODUCT` (`ID`),
  CONSTRAINT `fk_PRODUCTO_CATEGORIA1`
    FOREIGN KEY (`CATEGORY_ID`)
    REFERENCES `CATEGORY` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------
-- Table `yourpc_test`.`PRODUCT_LOCALE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRODUCT_LOCALE` (
	`ID` BIGINT NOT NULL AUTO_INCREMENT,
    `PRODUCT_ID` BIGINT NOT NULL,
    `LOCALE_ID` VARCHAR(40) NOT NULL,
	`NAME` VARCHAR(80) NOT NULL,
    `DESCRIPTION` VARCHAR(2048) NOT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE INDEX `PRODUCT_ID_LOCALE_ID_UNIQUE` (`PRODUCT_ID` ASC, `LOCALE_ID` ASC) VISIBLE,
    CONSTRAINT `fk_PRODUCT_PRODUCT_LOCALE`
		FOREIGN KEY (`PRODUCT_ID`)
		REFERENCES `yourpc_test`.`PRODUCT` (`ID`)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT `fk_PRODUCT_LOCALE_LOCALE`
		FOREIGN KEY (`LOCALE_ID`)
		REFERENCES `yourpc_test`.`LOCALE` (`ID`)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------
-- Table `ORDER_LINE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ORDER_LINE` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ORDER_ID` BIGINT NOT NULL,
  `PRODUCT_ID` BIGINT NOT NULL,
  `QUANTITY` SMALLINT NOT NULL,
  `PURCHASE_PRICE` DECIMAL(10,2) NOT NULL,
  `SALE_PRICE` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_ORDER_LINE_PRODUCT1_idx` (`PRODUCT_ID` ASC) VISIBLE,
  INDEX `fk_ORDER_LINE_ORDER1_idx` (`CUSTOMER_ORDER_ID` ASC) VISIBLE,
  CONSTRAINT `fk_ORDER_LINE_ORDER1`
    FOREIGN KEY (`CUSTOMER_ORDER_ID`)
    REFERENCES `CUSTOMER_ORDER` (`ID`),
  CONSTRAINT `fk_ORDER_LINE_PRODUCT1`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `PRODUCT` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ATTRIBUTE_DATA_TYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ATTRIBUTE_DATA_TYPE` (
  `ID` CHAR(3) NOT NULL,
  `NAME` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATTRIBUTE_TYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ATTRIBUTE_TYPE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ATTRIBUTE_DATA_TYPE_ID` CHAR(3) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_attribute_type_attribute_data_type1_idx` (`ATTRIBUTE_DATA_TYPE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_attribute_type_attribute_data_type1`
    FOREIGN KEY (`ATTRIBUTE_DATA_TYPE_ID`)
    REFERENCES `ATTRIBUTE_DATA_TYPE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `yourpc_test`.`ATTRIBUTE_TYPE_LOCALE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ATTRIBUTE_TYPE_LOCALE` (
	`ID` INT NOT NULL AUTO_INCREMENT,
    `ATTRIBUTE_TYPE_ID` INT NOT NULL,
    `LOCALE_ID` VARCHAR(40) NOT NULL,
    `NAME` VARCHAR(80) NOT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE INDEX (`NAME` ASC, `LOCALE_ID` ASC) VISIBLE,
    CONSTRAINT `fk_ATTRIBUTE_TYPE_ATTRIBUTE_TYPE_LOCALE`
		FOREIGN KEY (`ATTRIBUTE_TYPE_ID`)
        REFERENCES `yourpc_test`.`ATTRIBUTE_TYPE` (`ID`)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
	CONSTRAINT `fk_ATTRIBUTE_TYPE_LOCALE_LOCALE` 
		FOREIGN KEY (`LOCALE_ID`)
        REFERENCES `yourpc_test`.`LOCALE` (`ID`)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
	)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------
-- Table `ATTRIBUTE_VALUE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ATTRIBUTE_VALUE` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `ATTRIBUTE_TYPE_ID` INT NOT NULL,
  `VALUE_BIGINT` BIGINT NULL DEFAULT NULL,
  `VALUE_VARCHAR` VARCHAR(128) NULL DEFAULT NULL,
  `VALUE_DECIMAL` DECIMAL(20,8) NULL DEFAULT NULL,
  `VALUE_BOOLEAN` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ATTRIBUTE_TYPE_ID_VALUE_COLUMNS_UNIQUE` (
	`ATTRIBUTE_TYPE_ID` ASC,
    (COALESCE(`VALUE_BIGINT`, '')) ASC,
    (COALESCE(`VALUE_VARCHAR`, '')) ASC,
    (COALESCE(`VALUE_DECIMAL`, '')) ASC,
    (COALESCE(`VALUE_BOOLEAN`, '')) ASC
    ),
  INDEX `fk_attribute_value_attribute_type1_idx` (`ATTRIBUTE_TYPE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_attribute_value_attribute_type1`
    FOREIGN KEY (`ATTRIBUTE_TYPE_ID`)
    REFERENCES `ATTRIBUTE_TYPE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `RMA_STATE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RMA_STATE` (
  `ID` CHAR(3) NOT NULL,
  `NAME` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `DESCR_UNIQUE` (`NAME` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `RMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RMA` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ID` INT NOT NULL,
  `RMA_STATE_ID` CHAR(3) NOT NULL,
  `CREATION_DATE` DATETIME NOT NULL,
  `TRACKING_NUMBER` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_RETURN_RETURN_STATE1_idx` (`RMA_STATE_ID` ASC) VISIBLE,
  INDEX `fk_RMA_CUSTOMER1_idx` (`CUSTOMER_ID` ASC) VISIBLE,
  CONSTRAINT `fk_RETURN_RETURN_STATE1`
    FOREIGN KEY (`RMA_STATE_ID`)
    REFERENCES `RMA_STATE` (`ID`),
  CONSTRAINT `fk_RMA_CUSTOMER1`
    FOREIGN KEY (`CUSTOMER_ID`)
    REFERENCES `CUSTOMER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `RMA_ORDER_LINE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RMA_ORDER_LINE` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `RMA_ID` BIGINT NOT NULL,
  `ORDER_LINE_ID` BIGINT NOT NULL,
  `QUANTITY` SMALLINT NOT NULL,
  INDEX `fk_RETURN_has_ORDER_LINE_ORDER_LINE1_idx` (`ORDER_LINE_ID` ASC) VISIBLE,
  INDEX `fk_RETURN_has_ORDER_LINE_RETURN1_idx` (`RMA_ID` ASC) VISIBLE,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_RETURN_has_ORDER_LINE_ORDER_LINE1`
    FOREIGN KEY (`ORDER_LINE_ID`)
    REFERENCES `ORDER_LINE` (`ID`),
  CONSTRAINT `fk_RETURN_has_ORDER_LINE_RETURN1`
    FOREIGN KEY (`RMA_ID`)
    REFERENCES `RMA` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `TICKET_TYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TICKET_TYPE` (
  `ID` CHAR(3) NOT NULL,
  `NAME` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `DESCR_UNIQUE` (`NAME` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `TICKET_STATE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TICKET_STATE` (
  `ID` CHAR(3) NOT NULL,
  `NAME` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `DESCR_UNIQUE` (`NAME` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `TICKET`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TICKET` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ID` INT NOT NULL,
  `EMPLOYEE_ID` INT NULL DEFAULT NULL,
  `CREATION_DATE` DATETIME NOT NULL,
  `TICKET_STATE_ID` CHAR(3) NOT NULL,
  `TICKET_TYPE_ID` CHAR(3) NOT NULL,
  `PRODUCT_ID` BIGINT NULL,
  `TITLE` VARCHAR(80) NOT NULL,
  `DESCRIPTION` VARCHAR(2048) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_TICKET_TICKET_STATE1_idx` (`TICKET_STATE_ID` ASC) VISIBLE,
  INDEX `fk_TICKET_table11_idx` (`TICKET_TYPE_ID` ASC) VISIBLE,
  INDEX `fk_TICKET_CUSTOMER1_idx` (`CUSTOMER_ID` ASC) VISIBLE,
  INDEX `fk_TICKET_EMPLOYEE1_idx` (`EMPLOYEE_ID` ASC) VISIBLE,
  INDEX `fk_TICKET_PRODUCT1_idx` (`PRODUCT_ID` ASC) VISIBLE,
  CONSTRAINT `fk_TICKET_CUSTOMER1`
    FOREIGN KEY (`CUSTOMER_ID`)
    REFERENCES `CUSTOMER` (`ID`),
  CONSTRAINT `fk_TICKET_EMPLOYEE1`
    FOREIGN KEY (`EMPLOYEE_ID`)
    REFERENCES `EMPLOYEE` (`ID`),
  CONSTRAINT `fk_TICKET_table11`
    FOREIGN KEY (`TICKET_TYPE_ID`)
    REFERENCES `TICKET_TYPE` (`ID`),
  CONSTRAINT `fk_TICKET_TICKET_STATE1`
    FOREIGN KEY (`TICKET_STATE_ID`)
    REFERENCES `TICKET_STATE` (`ID`),
  CONSTRAINT `fk_TICKET_PRODUCT1`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `PRODUCT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `TICKET_MESSAGE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TICKET_MESSAGE` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `TICKET_ID` BIGINT NOT NULL,
  `CUSTOMER_ID` INT NULL DEFAULT NULL,
  `EMPLOYEE_ID` INT NULL DEFAULT NULL,
  `DATE` DATETIME NOT NULL,
  `TEXT` VARCHAR(2048) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_TICKET_MESSAGE_TICKET1_idx` (`TICKET_ID` ASC) VISIBLE,
  INDEX `fk_TICKET_MESSAGE_CUSTOMER1_idx` (`CUSTOMER_ID` ASC) VISIBLE,
  INDEX `fk_TICKET_MESSAGE_EMPLOYEE1_idx` (`EMPLOYEE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_TICKET_MESSAGE_CUSTOMER1`
    FOREIGN KEY (`CUSTOMER_ID`)
    REFERENCES `CUSTOMER` (`ID`),
  CONSTRAINT `fk_TICKET_MESSAGE_EMPLOYEE1`
    FOREIGN KEY (`EMPLOYEE_ID`)
    REFERENCES `EMPLOYEE` (`ID`),
  CONSTRAINT `fk_TICKET_MESSAGE_TICKET1`
    FOREIGN KEY (`TICKET_ID`)
    REFERENCES `TICKET` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `PRODUCT_ATTRIBUTE_VALUE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRODUCT_ATTRIBUTE_VALUE` (
  `PRODUCT_ID` BIGINT NOT NULL,
  `ATTRIBUTE_VALUE_ID` BIGINT NOT NULL,
  PRIMARY KEY (`PRODUCT_ID`, `ATTRIBUTE_VALUE_ID`),
  INDEX `fk_product_has_attribute_value_attribute_value1_idx` (`ATTRIBUTE_VALUE_ID` ASC) VISIBLE,
  INDEX `fk_product_has_attribute_value_product1_idx` (`PRODUCT_ID` ASC) VISIBLE,
  CONSTRAINT `fk_product_has_attribute_value_product1`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `PRODUCT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_attribute_value_attribute_value1`
    FOREIGN KEY (`ATTRIBUTE_VALUE_ID`)
    REFERENCES `ATTRIBUTE_VALUE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `CATEGORY_ATTRIBUTE_TYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CATEGORY_ATTRIBUTE_TYPE` (
  `CATEGORY_ID` SMALLINT NOT NULL,
  `ATTRIBUTE_TYPE_ID` INT NOT NULL,
  PRIMARY KEY (`CATEGORY_ID`, `ATTRIBUTE_TYPE_ID`),
  INDEX `fk_category_has_attribute_type_attribute_type1_idx` (`ATTRIBUTE_TYPE_ID` ASC) VISIBLE,
  INDEX `fk_category_has_attribute_type_category1_idx` (`CATEGORY_ID` ASC) VISIBLE,
  CONSTRAINT `fk_category_has_attribute_type_category1`
    FOREIGN KEY (`CATEGORY_ID`)
    REFERENCES `CATEGORY` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_category_has_attribute_type_attribute_type1`
    FOREIGN KEY (`ATTRIBUTE_TYPE_ID`)
    REFERENCES `ATTRIBUTE_TYPE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `TICKET_ORDER_LINE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TICKET_ORDER_LINE` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `TICKET_ID` BIGINT NOT NULL,
  `ORDER_LINE_ID` BIGINT NOT NULL,
  `QUANTITY` SMALLINT NOT NULL,
  INDEX `fk_TICKET_has_ORDER_LINE_ORDER_LINE1_idx` (`ORDER_LINE_ID` ASC) VISIBLE,
  INDEX `fk_TICKET_has_ORDER_LINE_TICKET1_idx` (`TICKET_ID` ASC) VISIBLE,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_TICKET_has_ORDER_LINE_TICKET1`
    FOREIGN KEY (`TICKET_ID`)
    REFERENCES `TICKET` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TICKET_has_ORDER_LINE_ORDER_LINE1`
    FOREIGN KEY (`ORDER_LINE_ID`)
    REFERENCES `ORDER_LINE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
